version: "3.8"
services:
  inversur-db-test:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Jimbo132
      POSTGRES_DB: test
    ports:
      - "5432:5432"

  inversur-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Jimbo132
      POSTGRES_DB: inversur
    ports:
      - "5433:5432"